services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: nutrient
      POSTGRES_PASSWORD: password
      POSTGRES_DB: nutrient
      POSTGRES_INITDB_ARGS: --data-checksums
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - pgdata:/var/lib/postgresql/data
  document_engine:
    image: "${DOCUMENT_ENGINE_IMAGE:-pspdfkit/document-engine:latest}"

    environment:
      PGUSER: nutrient
      PGPASSWORD: password
      PGDATABASE: nutrient
      PGHOST: db
      PGPORT: 5432

      # Activation key for your Nutrient Document Engine installation
      ACTIVATION_KEY: ${ACTIVATION_KEY}

      # Secret token used for authenticating API requests.
      API_AUTH_TOKEN: secret

      # Base key used for deriving secret keys for the purposes of authentication.
      SECRET_KEY_BASE: secret-key-base

      # Public key used for verification of JWTs from web clients. It has to be in the PEM format.
      JWT_PUBLIC_KEY: |
        -----BEGIN PUBLIC KEY-----
        MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAmOePeK068cxlRWt7Mgf0
        2VaxUhUQYVXo4/aa1ShZKBp7pHWl4JWzegjX09Y8Ltu2GO15n8s0x+2A3BBjIfHD
        xILrPrT+A7MRQwVrFOXCJr5LhXb6JA5VGW+TfTZsZd1lKg2Bnxz26A5pppjDIjVl
        Dt6KwcnQLeRAV6xZ/H01pIR884IXc6mX3kNxLFS0WcmbmgOCXv3aLCVbMSgubVvc
        Yel9CcpYipq7Pe04ArNHaqQWke8/E94tscJgZRfRD1ZolZGF98NMwMwMNe9G53Ug
        X2qYtrGSvhsW184brvmC5U69N2Czli5xazyloowpb/dHTjUkhYJkp/Jf5/rjH+pg
        RyUyKlxDXhNvpWAVA6UZdrVDCctYhokKiuV4A354L7mz0/cpFkIBzOZbquIBgNlJ
        lsHj5Jx+s9Dn5dvaBbddamE2JsOyTzLad8VuZaQtBOwZdFIn5o82fdtEWaZh3CBx
        9bymM73XrQXCQnfMSV1SARk7VRruxKnZHS1a8Yy27ppXYiFUw081otk8CECayufZ
        b/SbcsnEM7a5dEdVECA+mKLYgvl3fr/svy+6TbTEnHusj6Cngw9SO+4SyEeEd+nG
        6ZTjh2UWIAN4hQ3Wccuuq48hWPBo5bdMBDaTpUA/ZqLVU5EKkSnMPY1V4rG3Yu3Y
        0jeHR29ZIY18h2Pk/igZd1kCAwEAAQ==
        -----END PUBLIC KEY-----
      JWT_ALGORITHM: RS256

      # Credentials to access the admin dashboard
      DASHBOARD_USERNAME: dashboard
      DASHBOARD_PASSWORD: secret

      # Asset storage backend that is used by Nutrient Document Engine
      ASSET_STORAGE_BACKEND: built-in

      PORT: 4000
    depends_on:
      - db
    ports:
      - "4000:4000"
  example:
    platform: linux/amd64
    build: .
    environment:
      DOCUMENT_ENGINE_INTERNAL_URL: http://document_engine:4000
      DOCUMENT_ENGINE_EXTERNAL_URL: http://localhost:4000
      API_AUTH_TOKEN: secret
    depends_on:
      - document_engine
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app

volumes:
  pgdata:
